### ISSUE TITLE
Win 11 - Doesn't change Monitor

### ISSUE THREAD

**Issue by thomasfjen** [hansschmucker/NVStreamer1080#17]
Thank you for nice little tool! 
Sadly it doesn't work for me on Windows 11 when it should switch the monitor. It opens up the menu for switching the Monitor (Windows + P) but doesn't select the other Monitor. I guess that's a Windows 11 thing. 
Is there a way to fix that? 
![PXL_20230309_081245624](https://user-images.githubusercontent.com/47940833/223960917-41cda9e3-d1db-4784-825f-e33cc4bbe154.jpg)

**Comment by hansschmucker** [comment]
Hi Thomas
What it does when switching the display is really terribly simple:

DisplaySwitch.exe /external

It works for me, but I'm stuck at an old Win11 build due to my aging CPU.

You could try it via the run dialog and see if it works there. If it works there it could have something to do with access rights, but if it doesn't work there either you're probably right and MS has broken display switching in a recent build. Could you try and report the result please?

**Comment by thomasfjen** [comment]
Yep, exact same behavior. 

In the meantime i found an alternative solution and so far works great for me with the Monitorswitcher application and two profiles which are started before and after a stream by sunshine itself.
https://www.reddit.com/r/MoonlightStreaming/comments/11mqegm/guide_when_starting_sunshine_stream_to_turn_off/

**Comment by hansschmucker** [comment]
Whatever works ^^

Thanks for the pointer, I'll try to port over the way that application works. At least as an option.

--hans

**Comment by thomasfjen** [comment]
Jeah would be nice to have an alternative way to not add the commands to each game profile in sunshine. 👍

// Whoops I closed the issue
