### ISSUE TITLE
Restore the state of "Enhance Pointer Precision" in Windows

### ISSUE THREAD

**Issue by SuperLeiyan** [hansschmucker/NVStreamer1080#4]
This always gets turned on when nvstream starts, and for those who prefer it off, it's annoy to have to manually toggle it off after every stream session, it would be cool if this utility could restore the state of this too.
![image](https://user-images.githubusercontent.com/5438286/187071845-428a4f2c-9bae-465d-82ae-a1c0195b123a.png)

**Comment by hansschmucker** [comment]
That should be doable via http://www.pinvoke.net/default.aspx/user32/SystemParametersInfo.html ... not sure if it needs admin rights though. I'll check.

**Comment by hansschmucker** [comment]
[Release.zip](https://github.com/hansschmucker/NVStreamer1080/files/9446511/Release.zip)

First whack at this. If I'm not mistaken this needs admin rights so I'll probably hide it in the release until I decided on how to do process elevation... or maybe I'll simply hide the option unless you're starting it as administrator.

Since I don't have this issue I'm very happy about any feedback ^^

--hans

**Comment by hansschmucker** [comment]
Just released. It's only visible if you launch with admin rights. Closing.
